package com.project.PJA.user_act_log.enumeration;

public enum UserActionType {
    UPDATE_PARTICIPANT_TO_ACTION,
    CREATE_PROJECT_PROGRESS_ACTION,
    DELETE_PROJECT_PROGRESS_ACTION,
    DONE_PROJECT_PROGRESS_ACTION,
    UPDATE_PROJECT_PROGRESS_ACTION,
}
