package com.project.PJA.common.user_act_log;

public enum UserActionType {
    CREATE_WORKSPACE,
    UPDATE_WORKSPACE,
    DELETE_WORKSPACE,

    JOIN_WORKSPACE,

    CREATE_ERD,
    UPDATE_ERD,
    DELETE_ERD,

    CREATE_API,
    UPDATE_API,
    DELETE_API,

    CREATE_IDEA,
    UPDATE_IDEA,
    DELETE_IDEA,

    CREATE_PROJECT_PROGRESS_CATEGORY,
    UPDATE_PROJECT_PROGRESS_CATEGORY,
    DELETE_PROJECT_PROGRESS_CATEGORY,

    CREATE_PROJECT_PROGRESS_FEATURE,
    UPDATE_PROJECT_PROGRESS_FEATURE,
    DELETE_PROJECT_PROGRESS_FEATURE,

    CREATE_PROJECT_PROGRESS_ACTION,
    UPDATE_PROJECT_PROGRESS_ACTION,
    DELETE_PROJECT_PROGRESS_ACTION,

    UPDATE_PROJECT_PROGRESS_ACTION_POST,
    DELETE_PROJECT_PROGRESS_ACTION_POST,

    CREATE_PROJECT_PROGRESS_ACTION_COMMENT,
    UPDATE_PROJECT_PROGRESS_ACTION_COMMENT,
    DELETE_PROJECT_PROGRESS_ACTION_COMMENT,

    CREATE_REQUIREMENT,
    UPDATE_REQUIREMENT,
    DELETE_REQUIREMENT,

    UPDATE_PROJECT_INFO,
}
