package com.project.PJA.common.user_act_log;

public enum UserActionType {
    UPDATE_PARTICIPANT_TO_ACTION,
    CREATE_PROJECT_PROGRESS_ACTION,
    DELETE_PROJECT_PROGRESS_ACTION,
    DONE_PROJECT_PROGRESS_ACTION
}
